# Project Information
site_name: khanlab-NGS-Pipeline
site_author: Vineela Gangalapudi
site_description: >-
  The space will be used to provided documentation for khanlab NGS pipeline.

# Repository
repo_name: AWS_POC_MVP_NF
repo_url: https://github.com/CCRGeneticsBranch/Oncogenomics_NF_WF
edit_uri: https://github.com/CCRGeneticsBranch/Oncogenomics_NF_WF/docs

# Copyright
copyright: Copyright &copy; 2025 CCR Genetics Branch

# Configuration
theme:
  name: readthedocs
  custom_dir: overrides
plugins:
  - search
  - git-revision-date
  - minify:
      minify_html: true

# Markdown Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
extra_css:
  - overrides/extra.css
# Page Tree
nav:
  - Overview: index.md
  - Setting up Samplesheet: samplesheet.md
  - Running the Pipeline: pipeline_launch.md
  - Pipeline References & Tools: references.md
  - Dockers: dockers.md
